name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Pull latest changes from remote
        run: |
          git config --global user.name "Toulik-Das"
          git config --global user.email "dastoulik12@gmail.com"
          git pull --no-rebase https://Toulik:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Toulik/Meeting-Minutes main

      - name: Push changes to Hugging Face
        run: |
          git add .
          git commit -m "Your commit message"
          git push https://Toulik:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Toulik/Meeting-Minutes main
